### ISSUE TITLE
Codeblocks are not showing Tabs or 4 Spaces properly

### ISSUE THREAD

**Issue by toileto** [Jekyll-Garden/jekyll-garden.github.io#12]
Hi, thanks for this awesome theme, it's really beautiful!

Unfortunately, I found some bugs.

As python are sensitive regarding indentation, this theme is not showing the indentation properly. For example, below is the markdown.

![image](https://user-images.githubusercontent.com/33114786/143598400-4215032c-04e7-43f0-a4b2-9a40f1e64e32.png)

But when rendered, tabs are missing. I tried with both Tab and 4 spaces but they produced the same result no matter what.

![image](https://user-images.githubusercontent.com/33114786/143598484-fae4a921-ed38-4553-a3e9-7111e9fcea0e.png)

Overall, it's a beautiful theme and I really like it. I hope you can help to fix this bug to improve how tabs inside code blocks are rendered.

Thank you!

**Comment by hfactor** [comment]
Hi, I get the problem. I will check if there is some available solution.

**Comment by jwonyLee** [comment]
Hello, this comment can be a bit awkward using a translator. ;(
I think this problem is probably related to some styles in `style.css`.
Among them, it was confirmed that indentation occurs when the lower part is commented out. But I don't know which code specifically is causing the problem.
```css
code {
    font-family: Consolas, 'Courier New', Courier, monospace;
    display: inline-block;
    overflow: auto !important;
    white-space: pre-line !important;       
    word-wrap: break-word !important;       
    padding: 2px 2px  2px 2px;
    vertical-align:middle;
    padding: 2px 2px 2px 2px;
    border: 1px solid var(--secondary-border-color);
    border-radius: 4px;
}

.regular-sans code {
    padding: 20px;
    background-color: var(--bg-sub);
    border-radius: 5px;
    border: none;
}

.serif code {
    padding: 20px;
    background-color: var(--bg-sub);
    border-radius: 5px;
    border: none;
}

pre code {
    font-family: Consolas, 'Courier New', Courier, monospace;
    display: inline-block;
    overflow: auto !important;
    white-space: pre-line !important;       
    word-wrap: break-word !important;       
    padding: 15px 15px  15px 15px;
    vertical-align:middle;
    width: 90%;
    background-color: var(--bg-sub);
    border: 1px solid var(--secondary-border-color);
    border-radius: 5px;
    color: var(--text-main);
}
```
Hope this comment helps you fix the issue.
