### ISSUE TITLE
Setting the homepage/enabled parameter to false in _config.yml does not give the expected result.

### ISSUE THREAD

**Issue by An0d** [Jekyll-Garden/jekyll-garden.github.io#37]
Setting the homepage/enabled parameter to false should display the notes feed but it does not.

```yaml
# To enable a homepage, change the value to true and add content to _includes/Homepage.html
# If enable : false, notes feed will be as homepage. 
  homepage: 
    enabled: false ##If you need a homepage, change this to true and edit _includes/Homepage.html
```

This is the current result

![image](https://user-images.githubusercontent.com/16877886/209434991-f5bae366-87a5-48c6-b0e5-ba14a69e4cf1.png)

I will make a PR in order to fix that so the result will be is as follow

![image](https://user-images.githubusercontent.com/16877886/209435019-28c42f16-8280-4457-a77a-9a14ddb04c1b.png)

As we are on the homepage I removed the `← Home` link
